const SIZE=56,SAVE_KEY='sweet-merge-cafe-v1',MAX_ENERGY=60,ENERGY_MS=120000,MAX_MACHINE_LEVEL=11,DECORS_PER_CHAPTER=20,DECOR_XP=10;
const CHAINS={
  coffee:['咖啡豆袋','浓缩咖啡','冰咖啡','爱心拿铁','奶油卡布','典藏咖啡壶','香草摩卡','焦糖玛奇朵','海盐冷萃','玫瑰拿铁','彩虹咖啡','星空特调','黄金咖啡','大师咖啡礼盒','传说咖啡盛宴'],
  cake:['面粉袋','鸡蛋','草莓杯糕','草莓蛋糕','庆典蛋糕','焦糖布丁','奶油卷','马卡龙塔','蜂蜜松饼','蓝莓派','彩虹蛋糕','鲜花蛋糕','皇冠蛋糕','梦幻甜品桌','皇家庆典甜点'],
  fruit:['草莓','樱桃','苹果','蜜桃','葡萄','蓝莓','果汁杯','水果拼盘','鲜果沙拉','冰镇果饮','彩虹果昔','热带果碗','琉璃果盘','花园果篮','丰收水果盛宴'],
  tea:['茶叶罐','茶包','清茶杯','柠檬红茶','蜜桃乌龙','奶盖茶','花果茶','珍珠奶茶','抹茶拿铁','星光冰茶','桂花茶壶','节庆茶席','月光茶礼','大师茶宴','传说下午茶'],
  bread:['面团','黄油面包','牛角包','吐司','肉桂卷','果酱丹麦','蜂蜜贝果','芝士面包','水果派','编织面包','香草法棍','节庆面包篮','黄金可颂塔','大师烘焙礼盒','皇家面包盛宴'],
  icecream:['鲜奶','香草冰淇淋','草莓冰淇淋','巧克力圣代','薄荷冰杯','彩虹冰淇淋','水果雪葩','华夫冰淇淋','星星冰棒','梦幻冰淇淋塔','花园冰盘','月光冰甜品','水晶冰淇淋','大师冰品桌','传说冰淇淋派对'],
  chocolate:['可可豆','巧克力块','热巧克力','松露巧克力','巧克力棒','巧克力慕斯','榛子巧克力','巧克力喷泉','巧克力礼盒','彩绘巧克力','金箔松露','节庆巧克力塔','梦幻可可盘','大师巧克力宴','皇家巧克力庆典']
};
const TYPES=Object.keys(CHAINS),TYPE_NAMES={coffee:'咖啡机',cake:'烘焙机',fruit:'鲜果机',tea:'茶饮机',bread:'面包烤炉',icecream:'冰淇淋机',chocolate:'巧克力工坊'},TYPE_ICONS={coffee:'☕',cake:'🧁',fruit:'🍓',tea:'🫖',bread:'🥖',icecream:'🍨',chocolate:'🍫'};
const CHAPTERS=[
  {name:'暖糖咖啡屋',items:['招牌灯箱','甜品橱窗','绿植角','双人沙发','唱片机','花朵格栅']},
  {name:'露台甜品区',items:['露台灯牌','冰柜餐台','香草盆栽','藤编卡座','午后音响','蔷薇花架']},
  {name:'梦幻烘焙坊',items:['烘焙招牌','蛋糕展柜','香料绿植','试吃沙发','复古留声机','糖霜花墙']},
  {name:'花园咖啡角',items:['花园灯箱','下午茶柜','热带植物','花园软椅','音乐吧台','星灯花廊']}
];
const DECOR_ICONS=['💡','🧁','🪴','🛋️','🎵','🌸'];
const EXTRA_DECORS=[
  ['手写菜单墙','咖啡豆展示架','暖光吊灯','复古收银台','甜点展示盘','窗边吧台','格纹桌布','奶油色墙纸','木质置物架','咖啡香氛机','店员围裙墙','打卡霓虹灯','焦糖色地毯','花边窗帘'],
  ['遮阳伞座位','柠檬水吧台','玻璃甜品柜','藤编花篮','露台招牌旗','午后读物架','马卡龙托盘','微风风铃','粉色靠垫','露天小舞台','烛光小桌','草莓花盆','星星灯串','露台拍照墙'],
  ['黄油烤炉','面包冷却架','配方黑板','糖霜操作台','曲奇罐墙','烘焙手套架','擀面杖挂架','小麦壁画','香料抽屉','礼盒包装台','法式甜品灯','奶油地砖','生日蛋糕台','烘焙师奖章墙'],
  ['玻璃花房','藤蔓拱门','花园圆桌','薄荷饮品车','野餐点心篮','小鹿喷水池','薰衣草花圃','木栅栏灯','鸟语风铃','草莓苗圃','花园路牌','自然主题墙','晚霞灯带','萤火虫角落']
];
CHAPTERS.forEach((chapter,index)=>chapter.items.push(...EXTRA_DECORS[index]));
const DECORS=CHAPTERS.flatMap((ch,c)=>ch.items.map((name,i)=>[name,DECOR_ICONS[i%DECOR_ICONS.length],1+c+Math.floor(i/4),65+c*130+i*24,c*DECORS_PER_CHAPTER+i,c]));
const DECOR_LAYOUT=[[8,40,20,9],[36,69,24,5],[69,2,20,7],[71,35,28,6],[43,4,16,7],[12,73,22,5],[24,12,20,5],[24,58,18,5],[4,27,14,9],[50,66,25,6],[38,42,16,8],[73,15,25,5],[59,41,18,4],[20,43,15,4],[6,60,15,7],[57,63,18,6],[63,32,22,7],[40,23,18,6],[77,39,23,3],[75,75,20,7]];
let state,selected=null,history=[],dragFrom=null,touchDrag=null,ignoreTapUntil=0,timer,saveJob=null,sourceHint=null;
const $=s=>document.querySelector(s),board=$('#board');
function starterBoard(){const b=Array(SIZE).fill(null);TYPES.forEach((t,r)=>{b[r*7]={kind:'machine',type:t,level:0};b[r*7+1]={kind:'machine',type:t,level:0}});return b}
function fresh(){return{version:5,level:1,xp:0,coins:120,gems:20,stars:0,energy:40,energyAt:Date.now(),board:starterBoard(),orders:makeOrders(),decor:[],cafeChapter:0,pendingMachines:[],stats:{orders:0,merges:0,machines:0},tasks:{orders:0,merges:0,machines:0,produce:0,energy:0,decor:0},spendTotal:0,rechargeLog:[],updatedAt:Date.now()}}
function createOrder(){const count=1+Math.floor(Math.random()*3),items=[],maxLevel=Math.min(CHAINS.coffee.length-1,1+Math.floor((state?.stats?.orders||0)/9));while(items.length<count){const type=TYPES[Math.floor(Math.random()*TYPES.length)],level=Math.floor(Math.random()*(maxLevel+1));if(!items.some(x=>x.type===type&&x.level===level))items.push({type,level})}const reward=items.reduce((sum,x)=>sum+32+(x.level+1)*14,0);return {items,reward}}
function makeOrders(){return Array.from({length:6},()=>createOrder())}
function migrate(s){const oldVersion=Number(s?.version||0),d=fresh();s={...d,...s,stats:{...d.stats,...s.stats},tasks:{...d.tasks,...s.tasks}};s.board=(s.board||d.board).map(x=>x&&!x.kind?{...x,kind:'product'}:x);while(s.board.length<SIZE)s.board.push(null);s.pendingMachines=s.pendingMachines||[];if(!s.board.some(x=>x?.kind==='machine'))TYPES.forEach(type=>{for(let copy=0;copy<2;copy++){const p=s.board.indexOf(null);if(p>=0)s.board[p]={kind:'machine',type,level:0};else s.pendingMachines.push(type)}});if(oldVersion<5)TYPES.slice(3).forEach(type=>{if(s.board.some(x=>x?.kind==='machine'&&x.type===type))return;for(let copy=0;copy<2;copy++){const p=s.board.indexOf(null);if(p>=0)s.board[p]={kind:'machine',type,level:0};else s.pendingMachines.push(type)}});if(oldVersion<5&&Array.isArray(s.decor))s.decor=[...new Set(s.decor.map(i=>Math.floor(i/6)*DECORS_PER_CHAPTER+i%6))].filter(i=>i>=0&&i<DECORS.length);s.orders=(s.orders||[]).map(o=>o.items?{...o,items:o.items.slice(0,3)}:{items:[{type:o.type||'coffee',level:o.level||0}],reward:o.reward||50});while(s.orders.length<6)s.orders.push(createOrder());s.orders=s.orders.slice(0,6);s.version=5;return s}
function load(){try{state=migrate(JSON.parse(localStorage.getItem(SAVE_KEY))||fresh())}catch{state=fresh()}recoverEnergy();render()}
function save(){state.updatedAt=Date.now();clearTimeout(saveJob);saveJob=setTimeout(()=>{saveJob=null;localStorage.setItem(SAVE_KEY,JSON.stringify(state))},250)}
function flushSave(){clearTimeout(saveJob);saveJob=null;state.updatedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(state))}
function snapshot(){history.push(JSON.stringify(state));if(history.length>12)history.shift()}
function recoverEnergy(){if(state.energy>=MAX_ENERGY){state.energy=MAX_ENERGY;state.energyAt=Date.now();return}const now=Date.now(),gained=Math.floor((now-state.energyAt)/ENERGY_MS);if(gained>0){state.energy=Math.min(MAX_ENERGY,state.energy+gained);state.energyAt+=gained*ENERGY_MS}}
function itemArt(type,level){const illustrated=['tea','bread','icecream','chocolate'].includes(type)||(['coffee','cake','fruit'].includes(type)&&level<6);if(illustrated)return `<img class="item-art" src="assets/items/${type}-${level}.png" alt="${CHAINS[type][level]}" draggable="false">`;return `<span class="item-art item-token token-${type}" aria-label="${CHAINS[type][level]}"><i>${TYPE_ICONS[type]}</i><b>${level+1}</b></span>`}
function machineArt(x){if(['coffee','cake','fruit'].includes(x.type))return `<span class="machine-art type-${x.type}"><img src="assets/machines/${x.type}-${Math.min(MAX_MACHINE_LEVEL,x.level)}.png" alt="${TYPE_NAMES[x.type]}等级${x.level+1}" draggable="false"><em>${TYPE_NAMES[x.type]}</em><b>Lv.${x.level+1}</b></span>`;return `<span class="machine-art machine-token type-${x.type}"><i>${TYPE_ICONS[x.type]}</i><em>${TYPE_NAMES[x.type]}</em><b>Lv.${x.level+1}</b></span>`}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1900)}
function xpNeed(level){return 30+(level-1)*18+Math.floor((level-1)/3)*12}
function addXp(amount){state.xp+=amount;const rewards=[];while(state.xp>=xpNeed(state.level)){state.xp-=xpNeed(state.level);state.level++;const energy=8+Math.floor(state.level/2)*2,gems=2+Math.floor(state.level/3);state.energy=Math.min(MAX_ENERGY,state.energy+energy);state.energyAt=Date.now();state.gems+=gems;rewards.push(`Lv.${state.level} +${energy}⚡ +${gems}💎`)}return rewards}
function render(){recoverEnergy();placePendingMachine();$('#energy').textContent=state.energy;$('#coins').textContent=state.coins;$('#gems').textContent=state.gems;$('#stars').textContent=state.stars;$('#cafeStars').textContent=state.stars;$('#playerLevel').textContent=state.level;$('#xpProgress').textContent=`${state.xp}/${xpNeed(state.level)} XP`;renderBoard();renderOrders();if(!$('#cafeView').classList.contains('hidden'))renderCafe();if(!$('#tasksView').classList.contains('hidden'))renderTasks();renderMachineReward();renderBadges();updateTimer();$('#sellBtn').disabled=selected===null||!state.board[selected];$('#undoBtn').disabled=!history.length;save()}
function renderMachineReward(){const c=Math.min(state.cafeChapter,CHAPTERS.length-1),done=state.decor.filter(i=>Math.floor(i/DECORS_PER_CHAPTER)===c).length;$('#machineRewardText').textContent=`每完成 1 项装修：+${DECOR_XP} 经验并获得 1 台基础机器（本章 ${done}/${DECORS_PER_CHAPTER}）`;$('#machineRewardBar').style.width=`${done/DECORS_PER_CHAPTER*100}%`}
function renderBadges(){const taskReady=Object.entries(TASK_DEFS).some(([k,d])=>(state.tasks[k]||0)>=d[1]),max=(Math.min(CHAPTERS.length-1,Math.floor(state.decor.length/DECORS_PER_CHAPTER))+1)*DECORS_PER_CHAPTER,decorReady=DECORS.slice(0,max).some((d,i)=>!state.decor.includes(i)&&state.stars>=d[2]&&state.coins>=d[3]);$('#taskBadge').classList.toggle('hidden',!taskReady);$('#cafeBadge').classList.toggle('hidden',!decorReady)}
function renderBoard(){const orderNeeds=new Set(state.orders.flatMap(order=>order.items.map(item=>`${item.type}:${item.level}`)));state.board.forEach((x,i)=>{let b=board.children[i];if(!b){b=document.createElement('button');b.dataset.i=i;b.onclick=()=>{if(Date.now()>=ignoreTapUntil)tap(i)};b.ondragstart=e=>startDrag(e,i);b.ondragover=e=>dragOver(e,i);b.ondragleave=()=>b.classList.remove('drop-target');b.ondrop=e=>dropItem(e,i);b.ondragend=endDrag;b.ontouchstart=e=>startTouchDrag(e,i);b.ontouchmove=moveTouchDrag;b.ontouchend=endTouchDrag;b.ontouchcancel=cancelTouchDrag;board.appendChild(b)}const needed=x?.kind==='product'&&orderNeeds.has(`${x.type}:${x.level}`),className='cell'+(selected===i?' selected':'')+(x?.kind==='machine'?' machine-cell':'')+(needed?' order-needed':''),content=x?(x.kind==='machine'?machineArt(x):`${itemArt(x.type,x.level)}<span class="lv">${x.level+1}</span>`):'';if(b.className!==className)b.className=className;b.draggable=!!x;if(b.renderKey!==content){b.innerHTML=content;b.renderKey=content}});while(board.children.length>state.board.length)board.lastElementChild.remove()}
function reserveOrderItems(order){const used=new Set(),picked=[];for(const need of order.items){const index=state.board.findIndex((x,i)=>!used.has(i)&&x?.kind==='product'&&x.type===need.type&&x.level===need.level);if(index<0)return null;used.add(index);picked.push(index)}return picked}
function renderOrders(){closeNeedSource();const list=$('#orderList');state.orders.forEach((o,i)=>{const can=!!reserveOrderItems(o),content=`<div class="customer"><img src="assets/characters/customer-${i%3}.png" alt="顾客${i+1}"></div><div class="order-needs">${o.items.map(need=>{const ready=state.board.some(x=>x?.kind==='product'&&x.type===need.type&&x.level===need.level);return `<span class="need${ready?' ready':''}" title="${CHAINS[need.type][need.level]}" data-source-type="${need.type}">${itemArt(need.type,need.level)}<i>Lv.${need.level+1}</i></span>`}).join('')}</div><div>⭐ ${o.items.length}　🪙 ${o.reward}</div><button ${can?'':'disabled'} data-order="${i}">${can?'交付':'合成中'}</button>`;let d=list.children[i];if(!d){d=document.createElement('div');d.className='order';list.appendChild(d)}if(d.renderKey!==content){d.innerHTML=content;d.renderKey=content}d.querySelector('button').onclick=()=>deliver(i);d.querySelectorAll('[data-source-type]').forEach(need=>need.onclick=e=>{e.stopPropagation();showNeedSource(need,need.dataset.sourceType)})});while(list.children.length>state.orders.length)list.lastElementChild.remove()}
function closeNeedSource(){if(!sourceHint)return;sourceHint.remove();sourceHint=null}
function showNeedSource(anchor,type){closeNeedSource();const hint=document.createElement('div'),rect=anchor.getBoundingClientRect(),below=rect.top<92;hint.className=`machine-source-popover${below?' below':''}`;hint.innerHTML=`<b>${TYPE_ICONS[type]} ${TYPE_NAMES[type]}</b><small>由这台机器生产</small>`;document.body.appendChild(hint);hint.style.left=`${Math.max(78,Math.min(window.innerWidth-78,rect.left+rect.width/2))}px`;hint.style.top=`${below?rect.bottom+8:rect.top-8}px`;sourceHint=hint}
function renderMachines(){const dock=$('#machineDock');dock.innerHTML='<div class="dock-title">生产机器 <small>等级越高，产出高级素材的概率越高</small></div>';TYPES.forEach(type=>{const list=state.board.filter(x=>x?.kind==='machine'&&x.type===type),best=list.sort((a,b)=>b.level-a.level)[0],b=document.createElement('button');b.className=`machine-button ${type}`;b.disabled=!best||state.energy<1||!state.board.includes(null);b.innerHTML=best?`${machineArt(best)}<span>${TYPE_NAMES[type]}<small>高级产出 ${highChance(best.level)}% · -1⚡</small></span>`:`<b>缺少${TYPE_NAMES[type]}</b>`;b.onclick=()=>produce(type);dock.appendChild(b)})}
function highChance(level){return Math.min(92,18+level*7)}
function productLevel(machineLevel){const ceiling=Math.min(9,1+Math.floor(machineLevel*.8));let level=0;while(level<ceiling&&Math.random()<Math.max(.34,.57+machineLevel*.028-level*.045))level++;return level}
function nearestSpawnCell(machineIndex){const columns=7,row=Math.floor(machineIndex/columns),col=machineIndex%columns,empty=state.board.map((x,i)=>x?null:i).filter(i=>i!==null);return empty.map(i=>({i,d:Math.abs(Math.floor(i/columns)-row)+Math.abs(i%columns-col)})).sort((a,b)=>a.d-b.d||a.i-b.i)[0].i}
function produceFromMachine(machineIndex){recoverEnergy();const machine=state.board[machineIndex],empty=state.board.map((x,i)=>x?null:i).filter(x=>x!==null);if(!machine||machine.kind!=='machine')return;if(!empty.length)return toast('棋盘已满，请先合成或出售物品');if(state.energy<1)return openEnergyInfo();snapshot();const wasFull=state.energy>=MAX_ENERGY;state.energy--;if(wasFull)state.energyAt=Date.now();state.tasks.produce=(state.tasks.produce||0)+1;state.tasks.energy=(state.tasks.energy||0)+1;const i=nearestSpawnCell(machineIndex),level=productLevel(machine.level);state.board[i]={kind:'product',type:machine.type,level};selected=null;render();board.children[i].classList.add('merged');toast(`Lv.${machine.level+1} ${TYPE_NAMES[machine.type]}产出了${CHAINS[machine.type][level]}`)}
function sameMerge(a,b){if(!a||!b||a.kind!==b.kind||a.type!==b.type||a.level!==b.level)return false;return a.level<(a.kind==='machine'?MAX_MACHINE_LEVEL:CHAINS[a.type].length-1)}
function mergeAt(from,to){const a=state.board[from],b=state.board[to];if(!sameMerge(a,b))return false;snapshot();state.board[to]={...b,level:b.level+1};state.board[from]=null;if(b.kind==='machine'){state.stats.machines++;state.tasks.machines++;toast(`${TYPE_NAMES[b.type]}升级到 Lv.${b.level+2}！`)}else{state.stats.merges++;state.tasks.merges++;toast(`合成了${CHAINS[b.type][b.level+1]}！`)}selected=null;render();board.children[to].classList.add('merged');return true}
function tap(i){const x=state.board[i];if(!x){selected=null;render();return}if(x.kind==='machine'&&selected===null){produceFromMachine(i);return}if(selected===null){selected=i;render();return}if(selected===i){selected=null;render();return}if(!mergeAt(selected,i)){selected=i;render()}}
function startDrag(e,i){if(!state.board[i])return e.preventDefault();dragFrom=i;selected=i;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(i));requestAnimationFrame(()=>e.currentTarget.classList.add('dragging'))}
function dragOver(e,i){if(dragFrom===null||dragFrom===i)return;e.preventDefault();e.dataTransfer.dropEffect='move';e.currentTarget.classList.add('drop-target')}
function moveOrMerge(from,to){if(!Number.isInteger(from)||!Number.isInteger(to)||from===to||!state.board[from])return false;if(state.board[to]){if(sameMerge(state.board[from],state.board[to])){mergeAt(from,to);return true}snapshot();const held=state.board[from];state.board[from]=state.board[to];state.board[to]=held;selected=null;render();toast('物品已交换位置');return true}snapshot();state.board[to]=state.board[from];state.board[from]=null;selected=null;render();toast('物品已移动');return true}
function dropItem(e,to){e.preventDefault();const from=dragFrom??Number(e.dataTransfer.getData('text/plain'));document.querySelectorAll('.drop-target').forEach(x=>x.classList.remove('drop-target'));moveOrMerge(from,to);endDrag()}
function endDrag(){document.querySelectorAll('.dragging,.drop-target').forEach(x=>x.classList.remove('dragging','drop-target'));dragFrom=null}
function cellAtTouch(touch){const cell=document.elementFromPoint(touch.clientX,touch.clientY)?.closest('.cell');return cell?Number(cell.dataset.i):null}
function startTouchDrag(e,i){if(!state.board[i])return;const touch=e.touches[0];if(!touch)return;touchDrag={from:i,to:i,target:null,startX:touch.clientX,startY:touch.clientY,moved:false}}
function moveTouchDrag(e){if(!touchDrag)return;const touch=e.touches[0];if(!touch)return;const drag=touchDrag,distance=Math.hypot(touch.clientX-drag.startX,touch.clientY-drag.startY);if(!drag.moved&&distance<9)return;e.preventDefault();if(!drag.moved){drag.moved=true;board.children[drag.from]?.classList.add('dragging')}const to=cellAtTouch(touch),target=Number.isInteger(to)&&to!==drag.from?to:null;if(target===drag.target){drag.to=to;return}if(Number.isInteger(drag.target))board.children[drag.target]?.classList.remove('drop-target');if(Number.isInteger(target))board.children[target]?.classList.add('drop-target');drag.target=target;drag.to=to}
function endTouchDrag(e){if(!touchDrag)return;const drag=touchDrag;touchDrag=null;if(!drag.moved)return;e.preventDefault();ignoreTapUntil=Date.now()+500;const touch=e.changedTouches[0],to=touch?cellAtTouch(touch):drag.to;board.children[drag.from]?.classList.remove('dragging');if(Number.isInteger(drag.target))board.children[drag.target]?.classList.remove('drop-target');moveOrMerge(drag.from,Number.isInteger(to)?to:drag.to)}
function cancelTouchDrag(){if(!touchDrag)return;const drag=touchDrag;touchDrag=null;board.children[drag.from]?.classList.remove('dragging');if(Number.isInteger(drag.target))board.children[drag.target]?.classList.remove('drop-target')}
function deliver(i){const o=state.orders[i],picked=reserveOrderItems(o);if(!picked)return;snapshot();picked.forEach(index=>state.board[index]=null);state.coins+=o.reward;state.stars+=o.items.length;state.stats.orders++;state.tasks.orders++;state.orders[i]=createOrder();selected=null;render();toast(`订单完成：+${o.items.length}⭐ +${o.reward}金币`)}
function grantMachine(){const type=TYPES[Math.floor(Math.random()*TYPES.length)],p=state.board.indexOf(null);if(p>=0)state.board[p]={kind:'machine',type,level:0};else state.pendingMachines.push(type);return TYPE_NAMES[type]}
function placePendingMachine(){if(!state.pendingMachines?.length)return;const p=state.board.indexOf(null);if(p>=0)state.board[p]={kind:'machine',type:state.pendingMachines.shift(),level:0}}
function renderCafe(){const unlocked=Math.min(CHAPTERS.length-1,Math.floor(state.decor.length/DECORS_PER_CHAPTER));state.cafeChapter=Math.min(state.cafeChapter||0,unlocked);const c=state.cafeChapter,start=c*DECORS_PER_CHAPTER,end=start+DECORS_PER_CHAPTER,chapter=CHAPTERS[c],scene=$('#cafeScene'),ownedCount=state.decor.filter(i=>i>=start&&i<end).length;scene.className=`cafe-scene chapter-${c}${ownedCount===DECORS_PER_CHAPTER?' scene-finished':''}`;$('#cafeName').textContent=chapter.name;$('#chapterNav').innerHTML=CHAPTERS.map((x,i)=>`<button data-chapter="${i}" class="${i===c?'active':''}" ${i>unlocked?'disabled':''}>${i+1}. ${x.name}${i>unlocked?' 🔒':''}</button>`).join('');scene.innerHTML=`<div class="scene-title">${chapter.name}</div><div class="scene-counter"><span>${['今日甜点','露台限定','新鲜出炉','花园特饮'][c]}</span></div>`;DECORS.slice(start,end).forEach((d,j)=>{const i=start+j,art=d[4],layout=DECOR_LAYOUT[j];if(state.decor.includes(i))scene.innerHTML+=`<div class="decor" style="--decor-top:${layout[0]}%;--decor-left:${layout[1]}%;--decor-width:${layout[2]}%;--decor-z:${layout[3]}"><img src="assets/decor/decor-${art}.png" alt="${d[0]}"><small>${d[0]}</small></div>`});$('#decorList').innerHTML=DECORS.slice(start,end).map((d,j)=>{const i=start+j,art=d[4],owned=state.decor.includes(i),ok=state.stars>=d[2]&&state.coins>=d[3];return `<div class="decor-card ${owned?'owned':''}"><img src="assets/decor/decor-${art}.png" alt="${d[0]}"><div><b>${d[0]}</b><small>${owned?'已摆放 · 已领取机器':`⭐${d[2]}　🪙${d[3]} · +${DECOR_XP} XP 和基础机器`}</small></div><button ${owned||!ok?'disabled':''} data-decor="${i}">${owned?'完成':'装修'}</button></div>`}).join('');document.querySelectorAll('[data-decor]').forEach(b=>b.onclick=()=>buyDecor(+b.dataset.decor));document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{state.cafeChapter=+b.dataset.chapter;render()})}
function buyDecor(i){const d=DECORS[i];if(state.decor.includes(i)||state.stars<d[2]||state.coins<d[3])return;snapshot();state.stars-=d[2];state.coins-=d[3];state.decor.push(i);state.tasks.decor=(state.tasks.decor||0)+1;const levelRewards=addXp(DECOR_XP),machine=grantMachine(),chapter=d[5];if(state.decor.filter(x=>Math.floor(x/DECORS_PER_CHAPTER)===chapter).length===DECORS_PER_CHAPTER&&chapter<CHAPTERS.length-1)state.cafeChapter=chapter+1;render();toast(levelRewards.length?`${d[0]}完成！${levelRewards.join('，')}`:`${d[0]}完成：+${DECOR_XP} XP，获得 1 台${machine}！`)}
const TASK_DEFS={orders:['完成 8 个顾客订单',8,3,'🧾'],merges:['完成 50 次物品合成',50,3,'✨'],machines:['升级 4 次生产机器',4,4,'⚙️'],produce:['使用任意生产机器 80 次',80,3,'🍳'],energy:['消耗 120 点体力',120,3,'⚡'],decor:['完成 6 项咖啡屋装修',6,5,'🏡']};
function renderTasks(){$('#taskList').innerHTML=Object.entries(TASK_DEFS).map(([k,d])=>{const n=state.tasks[k]||0,done=n>=d[1];return `<div class="task"><span>${d[3]}</span><div><b>${d[0]}</b><small>${Math.min(n,d[1])}/${d[1]} · 奖励 💎${d[2]}</small><i><em style="width:${Math.min(100,n/d[1]*100)}%"></em></i></div><button ${done?'':'disabled'} data-task="${k}">${done?'领取':'进行中'}</button></div>`}).join('');document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>claimTask(b.dataset.task))}
function claimTask(k){const d=TASK_DEFS[k];if(state.tasks[k]<d[1])return;state.tasks[k]-=d[1];state.gems+=d[2];render();toast(`任务完成，获得 ${d[2]} 钻石`)}
function updateTimer(){const el=$('#energyTimer');if(state.energy>=MAX_ENERGY)el.textContent='已满';else{const left=ENERGY_MS-((Date.now()-state.energyAt)%ENERGY_MS),m=Math.floor(left/60000),s=Math.floor(left%60000/1000);el.textContent=`${m}:${String(s).padStart(2,'0')} +1`}}
function showModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}
function openEnergyInfo(){showModal(`<h2>⚡ 体力获得方式</h2><div class="source-list"><p><b>自然恢复</b><span>每 2 分钟恢复 1 点，上限 ${MAX_ENERGY}</span></p><p><b>钻石购买</b><span>8 钻石兑换 30 体力</span></p><p><b>升级奖励</b><span>后续店铺升级时补充体力</span></p></div><button class="modal-action" onclick="buyEnergy()">💎8　购买 30 体力</button>`)}
function openShop(){const packs=[[6,60],[30,330],[68,780],[128,1600],[328,4500],[648,9800]];showModal(`<h2>💎 钻石小铺</h2><div class="spend-total"><small>模拟累计充值</small><b>¥ ${Number(state.spendTotal||0).toFixed(2)}</b><span>仅为游戏记录，不会产生真实扣款</span></div><h3>资源兑换</h3><div class="shop-grid resource-shop"><button onclick="buyEnergy()"><b>⚡ +30</b><small>💎 8</small></button><button onclick="buyCoins()"><b>🪙 +300</b><small>💎 10</small></button></div><h3>模拟钻石礼包</h3><div class="pack-grid">${packs.map(p=>`<button onclick="fakeRecharge(${p[0]},${p[1]})"><b>💎 ${p[1]}</b><small>¥ ${p[0]}</small></button>`).join('')}</div><p class="shop-note">以上按钮不会调用支付，也不会真实收费；仅累计模拟消费金额，用于体验资源压力。</p>`)}
function buyEnergy(){if(state.gems<8)return toast('钻石不足，请完成任务');state.gems-=8;state.energy=Math.min(MAX_ENERGY,state.energy+30);state.energyAt=Date.now();$('#modal').classList.add('hidden');render();toast('获得 30 体力')}
function buyCoins(){if(state.gems<10)return toast('钻石不足，请完成任务');state.gems-=10;state.coins+=300;$('#modal').classList.add('hidden');render();toast('获得 300 金币')}
function fakeRecharge(price,gems){state.spendTotal=Number(state.spendTotal||0)+Number(price);state.gems+=Number(gems);state.rechargeLog.push({price:Number(price),gems:Number(gems),at:Date.now()});$('#modal').classList.add('hidden');render();toast(`模拟充值 ¥${price}：获得 ${gems} 钻石`)}
function switchView(view){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('.merge-view').forEach(x=>x.classList.toggle('hidden',view!=='merge'));$('#cafeView').classList.toggle('hidden',view!=='cafe');$('#tasksView').classList.toggle('hidden',view!=='tasks');if(view==='cafe')renderCafe();if(view==='tasks')renderTasks()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#energyInfo').onclick=openEnergyInfo;$('#shopBtn').onclick=openShop;$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.add('hidden')};document.addEventListener('click',closeNeedSource);window.addEventListener('scroll',closeNeedSource,true);
$('#sellBtn').onclick=()=>{if(selected===null)return;const x=state.board[selected];if(x.kind==='machine'&&x.level===0)return toast('最后的基础机器不建议出售');snapshot();state.coins+=(x.kind==='machine'?25:3)*(x.level+1);state.board[selected]=null;selected=null;render();toast('已出售')};
$('#undoBtn').onclick=()=>{if(!history.length)return;state=JSON.parse(history.pop());selected=null;render();toast('已撤销')};
$('#saveBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`甜甜合伙人存档-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('存档已导出')};
$('#loadInput').onchange=async e=>{try{state=migrate(JSON.parse(await e.target.files[0].text()));history=[];selected=null;render();toast('存档导入成功')}catch{toast('这不是有效的游戏存档')}e.target.value=''};
$('#resetBtn').onclick=()=>{if(confirm('确定重新开店？当前本地进度会被清空。')){state=fresh();history=[];selected=null;render()}};
window.buyEnergy=buyEnergy;window.buyCoins=buyCoins;window.fakeRecharge=fakeRecharge;timer=setInterval(()=>{const before=state.energy;recoverEnergy();updateTimer();if(state.energy!==before){$('#energy').textContent=state.energy;save()}},1000);window.addEventListener('pagehide',flushSave);load();
